// <auto-generated />
using System;
using HealthcareFhirApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareFhirApi.Infrastructure.Migrations
{
    [DbContext(typeof(FhirDbContext))]
    [Migration("20260401164237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthcareFhirApi.Infrastructure.Data.FhirResourceEntity", b =>
                {
                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint");

                    b.HasKey("ResourceType", "Id");

                    b.HasIndex("LastUpdated");

                    b.HasIndex("ResourceType");

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
