server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /lander {
        alias /usr/share/nginx/html/lander;
        index index.html;
        try_files $uri $uri/ /lander/index.html;
    }
}
